### POST /api/storyteller
POST http://localhost:3000/api/storyteller
Content-Type: application/json

{
  "imagesId": [
    "3aa24065-1339-4c15-ade9-ac630ebc843c"
  ],
  "theme": "halloween",
  "description": "30% de descuento"
}

  # "a321f180-cdcc-47ed-bea6-2dadae93457c", "ae8f1028-d3db-43ac-ad7d-2ae07e08840e", "d9275e30-d03b-4db0-a751-db02e4ba817c"
